-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0  # Use the ref you want to point at
    hooks:
        -   id: flake8
            additional_dependencies: [flake8-tidy-imports, flake8-mutable]
            exclude: .git,__pycache__,docs/source/conf.py,old,build,dist,migrations,*/settings/*,
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
