version: 2.1



commands:
  install_binaries:
    steps:
      - run:
          name: Installing binaries
          command: apt-get update && apt-get -y install build-essential wkhtmltopdf

  install_pip_env:
    steps:
      - install_binaries
      - run:
          name: Installing pip and pipenv
          command: pip install --upgrade pip && pip install --upgrade pipenv

jobs:
  test:
    environment:
      - PIPENV_CACHE_DIR: "~/.local/pipenv-cache"
      - DJANGO_SETTINGS_MODULE: portfolio.settings.testing
      - DATABASE_URL: sqlite://./db.sqlite3
      - GOOGLE_ANALYTICS_ID: UA-123456-7
    docker:
      - image: python:3.7.5
    steps:
      - checkout
      - install_pip_env
      - restore_cache:
          keys:
            - pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - pip-packages-v1-{{ .Branch }}-
            - pip-packages-v1-

      - run: pipenv install --system --deploy --ignore-pipfile --dev
      - save_cache:
          paths:
            - ~/.local/pipenv-cache
            - ~/.apt-cache
          key: pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run: pytest -n 2 --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results

workflows:
  main:
    jobs:
      - test
